data:
  path: /tmp/math_Qwen2-7B-Instruct.parquet
  prompt_key: prompt
  response_key: responses
  data_source_key: data_source
  reward_model_key: reward_model

trainer:
  wandb: False  # Set to True to enable wandb logging
  project_name: evaluation  # Project name for Weights and Biases; default is "evaluation".