# Sample configuration for the ICL reasoning script

# Define ICL examples configurations
icl_examples:
  # Example 1: Moons dataset with no flip rate
  - task_type: moons
    flip_rate: 0.0
    noise_type: 0.1
    shot_type: 50
    reslen_type: 3046
    nsamples_type: 500
    num_examples: 1
    icl_example_maxlength: 6000
  
  # Example 2: Moons dataset with 0.1 flip rate
  # - task_type: linear
  #   flip_rate: 0.0
  #   noise_type: 0.1
  #   shot_type: 50
  #   reslen_type: 3046
  #   nsamples_type: 500
  #   num_examples: 1
  #   icl_example_maxlength: 6000
  
  # Example 3: Circles dataset
  - task_type: circles
    flip_rate: 0.0
    noise_type: 0.0
    shot_type: 50
    reslen_type: 3046
    nsamples_type: 500
    num_examples: 1
    icl_example_maxlength: 6000
  
  - task_type: blobs
    flip_rate: 0.0
    noise_type: 1.0
    shot_type: 50
    reslen_type: 3046
    nsamples_type: 500
    num_examples: 1
    icl_example_maxlength: 6000

###Define test data configuration
test_data:
  task_type: linear
  flip_rate: 0.0
  noise_type: 0.1
  num_samples: 2000

###Test data examples configuration (for in-context examples)
test_data_examples:
  task_type: linear
  flip_rate: 0.0
  noise_type: 0.1
  shot_type: 50



# Random seeds for reproducibility
icl_example_seed: 42
test_data_seed: 42

# Tokenizer name for length calculation
tokenizer_name: Qwen/Qwen2.5-3B-Instruct

# Output path
output_path: /staging/szhang967/icl_datasets 